# Generated by Django 2.2.5 on 2019-05-19 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('restaurant_image', models.ImageField(default='resta.jpg', upload_to='restaurant_images/%Y/%m/%d/')),
                ('slug', models.SlugField(default='', editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Write the time like 19:30 or 7:30pm. And max input is 5 digits.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(blank=True, choices=[('R', 'Restaurant'), ('P', 'Person')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Table name or number.', max_length=100)),
                ('booked', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', editable=False)),
                ('booked_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_booked', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Time')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, null=True)),
                ('phone', models.CharField(help_text="including country code ex.'+1 xxx xxx xxxx'. ", max_length=16, null=True)),
                ('address', models.CharField(blank=True, help_text="Required, Ex.'Block D, Rd No.1, House 22/L, Bashundhara, Dhaka 1229' ", max_length=250)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/%d/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
